name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ethiohri-dev  # Replace with 'ethiohri-dev' if it's a valid custom runner

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository  # Ensure this is the correct path
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  # Cache key to invalidate when dependencies change
    - name: Build and install with Maven
      run: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version --file pom.xml
    - name: List files in target directory
      run: ls -al  /home/ubuntu/actions-runner-group/_work/openmrs-module-ethiohrireporting/openmrs-module-ethiohrireporting/omod/target
   
  publish:
    runs-on: ethiohri-dev  
    needs: build

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Updating module
      run: |
        sudo mv  /home/ubuntu/actions-runner-group/_work/openmrs-module-ethiohrireporting/openmrs-module-ethiohrireporting/omod/target/*.omod /usr/share/tomcat/tomcat8/.OpenMRS/modules/
    - name: Restarting server
      run: sudo systemctl restart tomcat8
